# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
###theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme"
# remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "31 days"
description: "Writing a PhD thesis in Computer Science in 31 days"
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
# logo: # path of site logo, e.g. "/images/logo.png"
logo: "/images/yinyang.png"
date_format: "%Y-%m-%d"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar

author:
  name   : "Gemma Danks"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Making sense of star stuff"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.gemmadanks.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/gemmadanks"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gemmadanks"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/gemmadanks/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gbdanks"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/gemmadanks"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gemmadanks"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/gemmadanks/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gbdanks"

defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Robert Johansson
  picture: /images/robert5.jpeg
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links: false
###  - title: Feed
###    url: atom.xml
###    icon: fas fa-rss-square

# Jekyll Scholar
scholar:
  style: current-opinion
  #bibliography_list_tag: 'div'
  #bibliography_item_tag: 'p'